- hosts: ragnar
  become: yes # execute as sudo
  vars:
    packages:
      - curl
#      - glances
#      - debian-keyring
#      - debian-archive-keyring
#      - apt-transport-https
#      - tldr
      - samba
      - samba-common
      - samba-client
#      - transmission-cli
#      - transmission-common
#      - transmission-daemon
#      - duf
#      - ca-certificates
#      - gnupg
#      - lsb-release
#      - apt-transport-https

  tasks:
    - name: dnf
      dnf:
        name: '{{ packages }}'
        update_cache: yes
        state: present # install if missing else skip it

    - name: Backup samba config
      command:
        cmd: cp /etc/samba/smb.conf /etc/samba/smb.conf_backup
        creates: /etc/samba/smb.conf_backup

    - name: Add custom samba config
      copy:
        src: "{{ playbook_dir }}/etc/smb.conf"
        dest: /etc/samba/smb.conf
        force: yes

    - name: Add [tim] samba config
      copy:
        src: "{{ playbook_dir }}/etc/tim.smb.conf"
        dest: /etc/samba/tim.smb.conf
        force: yes

    - name: Enable Samba/NetBIOS daemons
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - nmb
        - smb

    - name: Add Samba to firewall-cmd
      firewalld:
        service: samba
        permanent: yes
        state: enabled
