version: '3'

# default configuration
#networks:
#  default:
#    driver: bridge

services:
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - /var/data/redis:/data

  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - /var/data/mongo:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - '3001:8081'

  tyk-gateway:
    image: tykio/tyk-gateway
    container_name: tyk-gateway
    restart: unless-stopped
    ports:
      - '80:8080'
    volumes:
      - /var/data/tyk/tyk.conf:/opt/tyk-gateway/tyk.conf:ro
      - /var/data/tyk/apps:/opt/tyk-gateway/apps:ro
      - /var/data/tyk/middleware:/opt/tyk-gateway/middleware:ro
      - /var/data/tyk/certs:/opt/tyk-gateway/certs:ro
    depends_on:
      - redis
    # level=warning msg="Reconnecting storage: Redis is either down or ws not configured" prefix=pub-sub
    # ...
    # This message is ok if seen once or twice - the redis healthcheck from the gateway takes a few seconds to turn green.

  tyk-dashboard:
    image: tykio/tyk-dashboard
    container_name: tyk-dashboard
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - /var/data/tyk/tyk-dashboard.conf:/opt/tyk-dashboard/tyk_analytics.conf:ro

  hello:
    image: strm/helloworld-http
    container_name: hello
    restart: unless-stopped
    ports:
      - '80'

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    privileged: true
    restart: unless-stopped
    ports:
      - '9443'
    volumes:
      - /var/data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
  
  duc-client:
    image: entec/duc-client
    container_name: duc-client
    env_file: /var/ansible/run/duc.env
    restart: unless-stopped