#!/usr/bin/env fish

# omf theme
omf update
if ! omf list | grep eden > /dev/null
  omf install eden
end

# https://github.com/jorgebucaran/fisher#quickstart
# https://github.com/PatrickF1/fzf.fish
if ! type -q fisher
    curl -sL https://git.io/fisher | source
end

fisher install jorgebucaran/fisher \
  && fisher install jorgebucaran/nvm.fish \
  && fisher install PatrickF1/fzf.fish

cp -i ~/dev/linux-auto/fish/common.fish ~/dev/linux-auto/fish/linux.fish ~/.config/fish/
echo -s '
# ~~~~ WARNING: DO NOT EDIT THIS FILE ~~~~ #
set -x fish_conf "$HOME/.config/fish/config.fish"
source ~/.config/fish/linux.fish
' > ~/.config/fish/config.fish
source ~/.config/fish/config.fish

# setup nodejs
nvm install 18
corepack enable
corepack prepare pnpm@latest --activate
pnpm setup
