#!/bin/bash
curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source -
fisher install jorgebucaran/fisher

if [[ ! -d /Users/tim/.local/share/omf ]]; then
  curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish
fi


# fish script...
cat <<EOF | fish

# omf theme
omf update
if ! omf list | grep eden > /dev/null
  omf install eden
end

# https://github.com/jorgebucaran/fisher#quickstart
# https://github.com/PatrickF1/fzf.fish
if ! type -q fisher
    curl -sL https://git.io/fisher | source
end

fisher install jorgebucaran/fisher \
  && fisher install jorgebucaran/nvm.fish \
  && fisher install PatrickF1/fzf.fish

# setup nodejs
nvm install 18

EOF

cp ~/dev/linux-auto/fish/common.fish ~/dev/linux-auto/fish/linux.fish ~/.config/fish/
cat <<EOF > ~/.config/fish/config.fish
  # ~~~~ WARNING: DO NOT EDIT THIS FILE ~~~~ #
  source ~/.config/fish/linux.fish
EOF
source ~/.config/fish/config.fish
