sudo apt install -y \
  curl \
  xz-utils
  debian-keyring \
  debian-archive-keyring \
  apt-transport-https \
  ca-certificates \
  gnupg \
  lsb-release \
  software-properties-common \
  exa

sh <(curl -L https://nixos.org/nix/install) --no-daemon
. $HOME/.nix-profile/etc/profile.d/nix.sh

nix-env -i \
  curl \
  unzip \
  vim \
  fish \
  tldr \
  duf \
  bat \
  neofetch \
  git \
  diff-so-fancy \
  just

tldr -u

curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
  | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \
  && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" \
  | sudo tee /etc/apt/sources.list.d/ngrok.list \
  && sudo apt update \
  && sudo apt install ngrok

echo "source ~/.nix-profile/etc/profile.d/nix.sh" >> $HOME/.bashrc # todo: how to configure for fish?
source $HOME/.bashrc

# install nodejs
curl -fsSL https://fnm.vercel.app/install | bash
source $HOME/.bashrc
fnm install 18
fnm default 18

# install pnpm
corepack enable
corepack prepare pnpm@latest --activate
pnpm setup

# install git LFS
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
nix-env -i git-lfs

# https://developer.1password.com/docs/ssh/integrations/wsl/#forward-an-ssh-request
alias ssh='ssh.exe'
alias ssh-add='ssh-add.exe'
ssh -T git@github.com
ssh -T git@gitlab.com
git config --global core.sshCommand ssh.exe

git clone --local $HOME/dev/linux-auto git@github.com:tim-codes/linux-auto.git

# setup fish shell
curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source -
fisher install jorgebucaran/fisher

if [[ ! -d $HOME/.local/share/omf ]]; then
  curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish
fi

omf update
if ! omf list | grep eden > /dev/null
  omf install eden
end

# setup shell config sync-ing
rm $HOME/.config/fish/*.fish
cp $HOME/dev/linux-auto/fish/common.fish $HOME/dev/linux-auto/fish/linux.fish $HOME/.config/fish/
echo -s '
# ~~~~ WARNING: DO NOT EDIT THIS FILE ~~~~ #
set -x fish_conf "$HOME/.config/fish/config.fish"
source $HOME/.config/fish/linux.fish
' > $HOME/.config/fish/config.fish
source $HOME/.config/fish/config.fish