#!/usr/local/env bash

sudo apt install -y \
  curl \
  debian-keyring \
  debian-archive-keyring \
  apt-transport-https \
  ca-certificates \
  gnupg \
  lsb-release \
  apt-transport-https \
  software-properties-common \
  vim \
  fish \
  exa \
  tldr \
  duf \
  bat \
  neofetch \
  just \
  git

# install nodejs
curl -fsSL https://fnm.vercel.app/install | bash
fnm install 18
fnm default 18

# install pnpm
corepack enable
corepack prepare pnpm@latest --activate
pnpm setup

# setup fish shell
curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source -
fisher install jorgebucaran/fisher

if [[ ! -d /Users/tim/.local/share/omf ]]; then
  curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish
fi

omf update
if ! omf list | grep eden > /dev/null
  omf install eden
end

# setup shell config sync-ing
cp -i ~/dev/linux-auto/fish/common.fish ~/dev/linux-auto/fish/linux.fish ~/.config/fish/
echo -s '
# ~~~~ WARNING: DO NOT EDIT THIS FILE ~~~~ #
set -x fish_conf "$HOME/.config/fish/config.fish"
source ~/.config/fish/linux.fish
' > ~/.config/fish/config.fish
source ~/.config/fish/config.fish