- hosts: ragnar
  become: yes
  tasks:
    - name: Create app data directory
      shell:
        cmd: |
          mkdir -p /var/data
          chmod -R 777 /var/data
        creates: /var/data

    - name: Copy docker compose file to host
      copy:
        src: "{{ playbook_dir }}/../../server/docker-compose.yml"
        dest: /var/ansible/run/docker-compose.yml
        force: true

    - name: Copy tyk files
      copy:
        src: "{{ playbook_dir }}/../../server/tyk"
        dest: /var/data/
        force: yes
    
    - name: Copy DUC client config
      copy:
        src: "{{ playbook_dir }}/../../server/duc.env"
        dest: /var/ansible/run/duc.env
        force: true

    - name: Stand up docker services
      community.docker.docker_compose_v2:
        project_src: /var/ansible/run
        recreate: always # force recreate services
