- name: Install Transmission
  hosts: ragnar
  become: true # execute as sudo
  tasks:
    - name: Set download folder permissions
      ansible.builtin.shell:
        cmd: |
          sudo usermod -a -G debian-transmission tim
          sudo usermod -a -G smb-users debian-transmission
          sudo chgrp -R debian-transmission /mnt/store/transmission/
          sudo chmod 770 /mnt/store/transmission/

    - name: Stop Transmission
      ansible.builtin.service:
        name: transmission-daemon
        state: stopped

    - name: Configure Transmission
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../server/transmission.json"
        dest: /var/lib/transmission-daemon/info/settings.json
        force: true

    - name: Increase memory buffer for Transmission
      ansible.builtin.shell:
        cmd: |
          echo "net.core.rmem_max = 4194304" >> /etc/sysctl.conf
          echo "net.core.wmem_max = 1048576" >> /etc/sysctl.conf
          sysctl -p
          sysctl --system
        creates: /var/ansible/state/sysctl_mem

    - name: Start Transmission
      ansible.builtin.service:
        name: transmission-daemon
        state: started
