- hosts: all
  become: yes
  tasks:
    - name: Create app data directory
      shell:
        cmd: |
          mkdir -p /var/data
          chmod -R 777 /var/data
        creates: /var/data

    - name: Copy docker compose file to host
      copy:
        src: "{{ playbook_dir }}/../../server/docker-compose.yml"
        dest: /var/ansible/run/docker-compose.yml
        force: true

    - name: Copy tyk files
      copy:
        src: "{{ playbook_dir }}/../../server/tyk"
        dest: /var/data/
        force: yes

    - name: Stand up docker services
      docker_compose:
        project_src: /var/ansible/run
        recreate: always # force recreate services
